version: '3'

services:
  apache-php:
    build: ./php
    volumes:
      - ./:/var/www/html/
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8080:80"
    depends_on:
      - mysql
    links:
      - mysql


  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hillel